# -*- coding: utf-8 -*-
"""datascience_task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VrOqjYk_tI2979X_LsYCUc6WUFI-zCY-
"""

from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Upload files
uploaded = files.upload()

# Load datasets into pandas DataFrames
data1 = pd.read_csv('Unemployment in India.csv')


# Display the first few rows of each dataset
print(data1.head())

data2 = pd.read_csv('Unemployment_Rate_upto_11_2020.csv')
print(data2.head())

data1.columns = data1.columns.str.strip()
data2.columns = data2.columns.str.strip()

data1['Date'] = data1['Date'].str.strip()
data2['Date'] = data2['Date'].str.strip()

data1['Date'] = pd.to_datetime(data1['Date'], format='%d-%m-%Y')
data2['Date'] = pd.to_datetime(data2['Date'], format='%d-%m-%Y')

data2 = data2.drop(columns=['Region.1'])

data1_cleaned = data1.dropna()

print(data1_cleaned.describe())
print(data2.describe())

# Unemployment Rate Over Time
plt.figure(figsize=(12, 6))
sns.lineplot(data=data1_cleaned, x='Date', y='Estimated Unemployment Rate (%)', hue='Region')
plt.title('Unemployment Rate Over Time')
plt.show()

pre_covid = data1_cleaned[data1_cleaned['Date'] < '2020-03-01']
during_covid = data1_cleaned[data1_cleaned['Date'] >= '2020-03-01']

print("Pre-Covid Mean Unemployment Rate:", pre_covid['Estimated Unemployment Rate (%)'].mean())
print("During Covid Mean Unemployment Rate:", during_covid['Estimated Unemployment Rate (%)'].mean())

plt.figure(figsize=(22, 6))
sns.boxplot(data=data1_cleaned, x='Region', y='Estimated Unemployment Rate (%)')
plt.title('Regional Unemployment Rates')
plt.show()

